	<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0" />
		<title>{module_pagename}</title>
{module_webapps id="30263" filter="item" itemId="7616221" resultsPerPage="1" template="" collection="companyInfo"}
{% assign companyInfo = companyInfo.items[0] -%}
        <link rel="shortcut icon" href="/_assets/img/favicon.png" />
        <link rel="apple-touch-icon" href="/_assets/img/home_badge_64.png" />
        <link rel="apple-touch-icon-precomposed" href="/_assets/img/home_badge_64.png" />
        <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Source+Sans+Pro:300,400,600,700,900" rel="stylesheet">
        
        <!--build:css css/styles.min.css-->
        <link rel="stylesheet" href="../../_assets/css/fontello/css/fontello.css" />
        <link rel="stylesheet" href="../../_assets/css/font-awesome.min.css" />
        <link rel="stylesheet" href="../../_assets/css/normalize.css" />
        <link rel="stylesheet" href="../../_assets/css/foundation.min.css" />
        <link href='../../_assets/css/slick.css' rel='stylesheet' type='text/css'> 
		<link href='../../_assets/css/ion.rangeSlider.css' rel='stylesheet' type='text/css'>
        <link href="../../_assets/css/styles.css" rel="stylesheet" type="text/css">	
        <!--endbuild-->
		
        
        <script src="//cdn.jsdelivr.net/combine/gh/jquery/jquery@1.11.1/dist/jquery.min.js,gh/GREGG-CHRISTOFFERSON/modernizr@v2.8.3/modernizr.min.js"></script>
	<!--[if lt IE 9]>
        <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.2/html5shiv.js"></script>
        <script src="//s3.amazonaws.com/nwapi/nwmatcher/nwmatcher-1.2.5-min.js"></script>
        <script src="//html5base.googlecode.com/svn-history/r38/trunk/js/selectivizr-1.0.3b.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/respond.js/1.1.0/respond.min.js"></script>
	<![endif]-->      
{% include"/_System/Includes/global-variables.inc" %}
{% include"/_System/Includes/regions.inc" %}     
 









