
<!--build:js js/main.min.js -->
<script src="../../_assets/js/foundation.min.js"></script> 
<script src="../../_assets/js/slick.min.js"></script>
<script src="../../_assets/js/ion.rangeSlider.js"></script> 
<script src="../../_assets/js/scripts.js"></script>
<script src="../../_assets/js/main.js"></script>
<!-- endbuild -->
<script>
      $(document).foundation();
    </script> 
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.matchHeight/0.7.2/jquery.matchHeight-min.js"></script>   
