{% comment -%}<!--Optimized js from gulp task building from files in _assets/includes/scripts-dev.inc-->{% endcomment -%}
<script type="text/javascript">
    /* First CSS File */
    var giftofspeed = document.createElement('link');
    giftofspeed.rel = 'stylesheet';
    giftofspeed.href = 'https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Source+Sans+Pro:300,400,600,700,900';
    giftofspeed.type = 'text/css';
    var godefer = document.getElementsByTagName('link')[0];
    godefer.parentNode.insertBefore(giftofspeed, godefer);
</script>
<script src="../../_assets/js/main.min.js"></script>
{% comment -%}<script src="//cdn.jsdelivr.net/gh/GREGG-CHRISTOFFERSON/rentpfi@v0.1.1/_assets/js/main.min.js"></script>{% endcomment -%}
<script>
      $(document).foundation();
    </script> 

<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.matchHeight/0.7.2/jquery.matchHeight-min.js"></script>
